//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvikLimbasiya_0415.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int Credit_Id { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> CreditAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
