//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvikLimbasiya_0415.Models.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameReward_0415Entities : DbContext
    {
        public GameReward_0415Entities()
            : base("name=GameReward_0415Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Wallet> Wallet { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<Dabit> Dabit { get; set; }
        public virtual DbSet<TransactionsHistory> TransactionsHistory { get; set; }
    }
}
