//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DhruvikLimbasiya_0415.Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int Wallet_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> DebitAmount { get; set; }
        public Nullable<int> creditAmout { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public Nullable<System.DateTime> DebitDate { get; set; }
        public Nullable<int> RemainingChance { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
